
export const REACT_APP_SUPABASE_URL = "https://afskqkyhnetxzrojffot.supabase.co"
// export const REACT_APP_SUPABASE_URL = "https://axwqqoifubxkipmilrmm.supabase.co"
// export const REACT_APP_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldnZqeHh0a2JwYXJvYWZhaXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njc0MDIxOTIsImV4cCI6MTk4Mjk3ODE5Mn0.xw_5PfSMp22L9VEB_56Wf8DQbXd161I3TZqjUKYjzK0'
export const REACT_APP_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmc2txa3lobmV0eHpyb2pmZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODYwMDAxNjMsImV4cCI6MjAwMTU3NjE2M30.HJ1lGrQRu7ETNjPTxts3L-WU4oiDdnLgCb36ZF8JOFg"

