
export const REACT_APP_SUPABASE_URL = "https://ojbvpzculnvfvrhsthso.supabase.co"
export const REACT_APP_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qYnZwemN1bG52ZnZyaHN0aHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQ0OTM5NTMsImV4cCI6MjAwMDA2OTk1M30.xA_R-juOnA5I-FTm0lB5V6acZND5Y3pD_2miTgIlCkw"
// export const REACT_APP_SUPABASE_URL = "https://afskqkyhnetxzrojffot.supabase.co"
// export const REACT_APP_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmc2txa3lobmV0eHpyb2pmZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODYwMDAxNjMsImV4cCI6MjAwMTU3NjE2M30.HJ1lGrQRu7ETNjPTxts3L-WU4oiDdnLgCb36ZF8JOFg"

